name: 'Fusion App Publish'
description: 'Authenticate & publish Fusion app using fusion-framework-cli'
author: 'Equinor Fusion Core'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  fusion-token:
    description: 'Pre-acquired Fusion bearer token (alternative to Azure auth)'
    required: false

  azure-client-id:
    description: 'Azure Client ID (for Service Principal or OIDC)'
    required: false

  azure-tenant-id:
    description: 'Azure Tenant ID'
    required: false

  azure-resource-id:
    description: 'Fusion audience/resource ID (for token acquisition)'
    required: false

  env:
    description: 'Target environment (ci/fqa/fprd/tr/next) or "ci" for PR-based selection'
    default: 'ci'
    required: false

  prNR:
    description: 'Pull Request number (used if env is "ci")'
    required: false

  artifact:
    description: 'Path to built artifact (default: ./app-bundle.zip)'
    required: false
    default: './app-bundle.zip'

  tag:
    description: 'Tag to apply to the deployment'
    required: false
    default: 'latest'

  working-directory:
    description: 'Working directory'
    required: false
    default: '.'


outputs:
  app-url:
    description: 'Direct URL to the published application'
    value: ${{ steps.publish.outputs.app-url }}
  
  portal-url:
    description: 'Fusion portal URL for managing the application'
    value: ${{ steps.publish.outputs.portal-url }}
  
  target-env:
    description: 'Resolved target environment (useful with auto mode)'
    value: ${{ steps.validate-env.outputs.env }}
  
  app-name:
    description: 'Application name from package.json'
    value: ${{ steps.metadata.outputs.app-name }}
  
  app-version:
    description: 'Application version from package.json'
    value: ${{ steps.metadata.outputs.app-version }}
  
  publish-info:
    description: 'Formatted publish information for PR comments'
    value: ${{ steps.metadata.outputs.publish-info }}

  auth-type:
    description: 'Authentication type used (token or service-principal)'
    value: ${{ steps.validate-auth.outputs.auth-type }}
    
  is-token:
    description: 'Whether fusion-token authentication was used (deprecated, use auth-type)'
    value: ${{ steps.validate-auth.outputs.isToken }}
    
  is-service-principal:
    description: 'Whether Azure Service Principal authentication was used'
    value: ${{ steps.validate-auth.outputs.isServicePrincipal }}

runs:
  using: 'composite'
  steps:

    - name: Validate Artifact
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: node ${{ github.action_path }}/dist/validate-artifact.cjs
      env:
        INPUT_ARTIFACT: ${{ inputs.artifact }}

    - name: Validate Environment
      id: validate-env
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: node ${{ github.action_path }}/dist/validate-env.cjs
      env:
        INPUT_PRNR: ${{ inputs.prNR }}
        INPUT_ENV: ${{ inputs.env }}
        INPUT_TAG: ${{ inputs.tag }}
        
    - name: Validate Is Token or Azure Auth Provided
      id: validate-auth
      shell: bash
      run: node ${{ github.action_path }}/dist/validate-is-token-or-azure.cjs
      env:
        INPUT_FUSION_TOKEN: ${{ inputs.fusion-token }}
        INPUT_AZURE_CLIENT_ID: ${{ inputs.azure-client-id }}
        INPUT_AZURE_TENANT_ID: ${{ inputs.azure-tenant-id }}
        INPUT_AZURE_RESOURCE_ID: ${{ inputs.azure-resource-id }}

    - name: Azure Login (if SP)
      if: steps.validate-auth.outputs.isToken == 'false'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        allow-no-subscriptions: true

    - name: Acquire token (if SP)
      if: steps.validate-auth.outputs.isToken == 'false'
      id: token
      shell: bash
      run: |
        TOKEN=$(az account get-access-token --resource "${{ inputs.azure-resource-id }}" --query accessToken -o tsv)
        echo "FUSION_TOKEN=$TOKEN" >> $GITHUB_ENV
        echo "::add-mask::$TOKEN"

    - name: Set token from input
      if: steps.validate-auth.outputs.isToken == 'true'
      shell: bash
      run: |
        echo "FUSION_TOKEN=${{ inputs.fusion-token }}" >> $GITHUB_ENV
        echo "::add-mask::${{ inputs.fusion-token }}"

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        package-manager-cache: false

    - name: Publish
      id: publish
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        FUSION_TOKEN: ${{ env.FUSION_TOKEN }}
        INPUT_ARTIFACT: ${{ inputs.artifact }}
      run: |
        npx fusion-framework-cli app publish \
          --env "${{ steps.validate-env.outputs.env }}" \
          --tag "${{ steps.validate-env.outputs.tag }}" \
          "${{ inputs.artifact }}" \

    - name: Check Meta Comment
      id: check-meta
      shell: bash
      run: node ${{ github.action_path }}/dist/check-meta-comment.cjs
      env:
        INPUT_TAG: ${{ steps.validate-env.outputs.tag }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Post Publish Metadata
      id: metadata
      if: steps.check-meta.outputs.exists == 'false'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: node ${{ github.action_path }}/dist/post-publish-metadata.cjs
      env:
        INPUT_ARTIFACT: ${{ inputs.artifact }}
        INPUT_ENV: ${{ steps.validate-env.outputs.env }}
        INPUT_TAG: ${{ steps.validate-env.outputs.tag }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Azure Logout (cleanup)
      if: ${{ always() && steps.validate-auth.outputs.isToken == 'false' }}
      shell: bash
      run: az logout