name: Bug Report
description: Report a bug in the Fusion App Publish Action
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the following information to help us investigate.

  - type: input
    id: action-version
    attributes:
      label: Action Version
      description: What version of the action are you using?
      placeholder: "v1.2.3 or commit SHA"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Fusion Environment
      description: Which Fusion environment were you targeting?
      options:
        - CI
        - FQA  
        - FPRD
        - TR
        - Custom (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: auth-method
    attributes:
      label: Authentication Method
      description: How were you authenticating?
      options:
        - Pre-acquired Fusion token
        - Azure Service Principal
        - Azure OIDC/Federated credentials
    validations:
      required: true

  - type: textarea
    id: workflow-config
    attributes:
      label: Workflow Configuration
      description: Please share your GitHub Actions workflow step (remove any secrets)
      render: yaml
      placeholder: |
        - name: Publish to Fusion
          uses: equinor/fusion-action-app-publish@v1
          with:
            env: 'ci'
            artifact: 'dist'
            # ... other inputs
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste the relevant error logs from your GitHub Actions run
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have removed any sensitive information from logs and configuration
          required: true
        - label: I am using a supported Node.js version (18+) in my workflow
          required: false