name: PR Preview Deployments

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

permissions:
  id-token: write
  contents: read
  pull-requests: write  # For commenting on PRs

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy PR Preview
        id: deploy
        uses: equinor/fusion-action-app-publish@v1
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          fusion-resource-id: ${{ secrets.FUSION_RESOURCE_ID }}
          env: 'ci'  # Will create pr-{number} environment when prNR is detected
          artifact: './app-bundle.zip'
        
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = `## 🚀 Preview Deployment
            
            **Environment:** \`${{ steps.deploy.outputs.environment }}\`
            **App URL:** ${{ steps.deploy.outputs.app-url && format('[Open Preview]({0})', steps.deploy.outputs.app-url) || 'Not available' }}
            **Portal URL:** ${{ steps.deploy.outputs.portal-url && format('[Manage in Portal]({0})', steps.deploy.outputs.portal-url) || 'Not available' }}
            
            **Details:**
            ${{ steps.deploy.outputs.publish-details }}
            
            ---
            *Deployed from commit ${{ github.sha }}*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

  cleanup-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR Cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const output = `## 🧹 Preview Cleanup
            
            Preview deployment for \`pr-${{ github.event.pull_request.number }}\` should be cleaned up.
            
            > **Note:** Automatic cleanup is not implemented yet. Please manually remove the deployment if needed.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });